# Generated by Django 2.0.5 on 2018-05-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingspots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='spots',
            new_name='Spot',
        ),
    ]
